import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { SiteFooter } from "@/components/site-footer";
import { Button } from "@/components/ui/button";
import engineerImage from "@/assets/ups-engineer.jpg";

export const Route = createFileRoute("/about")({
  head: () => ({ meta: [{ title: "About UPS Spe | Power Protection Specialists" }, { name: "description", content: "Learn how UPS Spe approaches UPS systems, power continuity, maintenance, and technical service." }, { property: "og:title", content: "About UPS Spe" }, { property: "og:description", content: "A practical, lifecycle-focused approach to power protection." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/about" }] }), component: About,
});
function About(){return <main><PageHero eyebrow="About UPS Spe" title="Power continuity begins with sound technical decisions." description="UPS Spe supports organizations that depend on reliable power, with a practical approach spanning planning, installation, maintenance, and recovery."/><section className="py-24"><div className="section-shell grid items-center gap-12 lg:grid-cols-2"><div><p className="eyebrow">Our approach</p><h2 className="mt-4 text-4xl font-semibold leading-tight">Focused on the system, the site, and the operating reality.</h2><p className="mt-6 leading-7 text-muted-foreground">A UPS is only one part of power continuity. Capacity, batteries, bypass arrangements, load conditions, environment, maintenance, and operator readiness all affect the result. We consider those connections before recommending work.</p><div className="mt-8 grid gap-4">{["Requirements before recommendations","Clear scope and practical next steps","Testing and documented handover","Maintenance planned around operating risk"].map(x=><div key={x} className="flex items-center gap-3 font-semibold"><CheckCircle2 className="size-5 text-primary"/>{x}</div>)}</div></div><img src={engineerImage} alt="UPS equipment inspection" width="1400" height="1000" loading="lazy" className="aspect-[4/3] w-full object-cover"/></div></section><section className="border-y border-border bg-secondary py-20"><div className="section-shell grid gap-10 md:grid-cols-3"><Value n="01" title="Technical clarity" text="Explain risks, options, and trade-offs in language decision-makers can use."/><Value n="02" title="Controlled execution" text="Define the scope, confirm the plan, and verify the outcome before handover."/><Value n="03" title="Lifecycle thinking" text="Consider maintainability, batteries, capacity, and future requirements—not only today’s fault."/></div></section><section className="py-20"><div className="section-shell flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><p className="eyebrow">Talk to a specialist</p><h2 className="mt-3 text-3xl font-semibold">Start with your operating requirement.</h2></div><Button asChild size="xl"><Link to="/contact">Request a consultation <ArrowRight/></Link></Button></div></section><SiteFooter/></main>}
function Value({n,title,text}:{n:string;title:string;text:string}){return <article><span className="font-mono text-sm text-primary">{n}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></article>}